config/routes.rb
Chamber::Application.routes.draw do
  resources :books do
    resources :chapters do
      resources :sentences
    end
  end

end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :chapters
  validates_presence_of :title
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  belongs_to :book
  has_many :sentences
end

app/models/sentence.rb
class Sentence < ActiveRecord::Base
  belongs_to :chapter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper :layout
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i(show edit update destroy)

  # GET /books
  # GET /books.xml
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.xml
  def show
  end

  # GET /books/new
  # GET /books/new.xml
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.xml
  def create
    if @book.save
      redirect_to(books_url)
    else
      render action: 'new'
    end
  end

  # PUT /books/1
  # PUT /books/1.xml
  def update
    if @book.update_attributes(book_params)
      redirect_to(books_url)
    else
      render action: 'edit'
    end
  end

  # DELETE /books/1
  # DELETE /books/1.xml
  def destroy
    @book.destroy
    redirect_to(books_url)
  end

  private

  def set_book
    @book = Book.find(params[:id])
  end

  def book_params
    params[:book]
  end
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  expose(:book)
  expose(:chapters) { book.chapters.all }
  expose(:chapter)
  before_action :assciation_bulder, only: [:create, :update]
  # GET /chapters
  # GET /chapters.xml
  def index
  end

  # GET /chapters/1
  # GET /chapters/1.xml
  def show
  end

  # GET /chapters/new
  # GET /chapters/new.xml
  def new
  end

  # GET /chapters/1/edit
  def edit
  end

  # POST /chapters
  # POST /chapters.xml
  def create
    if chapter.save
      redirect_to(book_chapter_sentences_path(book, chapter), notice: 'Chapter was successfully created.')
    else
      render action: 'new'
    end
  end

  # PUT /chapters/1
  # PUT /chapters/1.xml
  def update
    debugger
    chapter.book = book
    if chapter.save
      redirect_to(book_chapter_path([book, chapter]), notice: 'Chapter was successfully updated.')
    else
      render action: 'edit'
    end
  end

  # DELETE /chapters/1
  # DELETE /chapters/1.xml
  def destroy
    chapter.destroy
    redirect_to book_chapters_path(book)
  end

  private

  def assciation_bulder
  end
end

app/controllers/sentences_controller.rb
class SentencesController < ApplicationController
  expose(:book)
  expose(:chapters) { book.chapters.all }
  expose(:chapter)
  expose(:sentences) { chapter.sentences.all }
  expose(:sentence)
  # GET /sentences
  # GET /sentences.xml
  def index
  end

  # GET /sentences/1
  # GET /sentences/1.xml
  def show
  end

  # GET /sentences/new
  # GET /sentences/new.xml
  def new
  end

  # GET /sentences/1/edit
  def edit
  end

  # POST /sentences
  # POST /sentences.xml
  def create
    sentence.chapter = chapter
    if sentence.save
      redirect_to([book, chapter, sentence], notice: 'Sentence was successfully created.')
    else
      render action: 'new'
    end
  end

  # PUT /sentences/1
  # PUT /sentences/1.xml
  def update
    if sentence.save
      redirect_to(sentence, notice: 'Sentence was successfully updated.')
    else
      render action: 'edit'
    end
  end

  # DELETE /sentences/1
  # DELETE /sentences/1.xml
  def destroy
    sentence.destroy
    redirect_to book_chapter_sentences_path(book, chapter)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", default: 'Invalid Fields')
    options[:message] ||= I18n.t(:"activerecord.errors.message", default: 'Correct the following errors and try again.')
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, class: 'error_messages') do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/sentences_helper.rb
module SentencesHelper
end

app/views/books/_form.html.haml
= simple_form_for(@book) do |f|
  = f.input :title
  = f.input :tag
  = f.button :submit

app/views/books/edit.html.haml
%h1 Editing book

= render 'form'

= link_to 'Show', @book
|
= link_to 'Back', books_path

app/views/books/index.html.haml
%h1 Listing books

%table
  %tr
    %th Title
    %th Tag
    %th
    %th
    %th
  - @books.each do |book|
    %tr
      %td= book.title
      %td= book.tag
      %td= link_to 'Show', book_chapters_path(book)
      %td= link_to 'Edit', edit_book_path(book)
      %td= link_to 'Destroy', book, :confirm => 'Are you sure?', :method => :delete
%br
= link_to 'New Book', new_book_path

app/views/books/new.html.haml
%h1 New book

= render 'form'

= link_to 'Back', books_path

app/views/books/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @book.title

%p
  %b Version:
  = @book.version
-unless @book.chapters.blank?
  -for chapter in @book.chapters
    %p=link_to chapter.title, [@book, chapter]

= link_to 'Edit', edit_book_path(@book)
|
= link_to 'Back', books_path

app/views/chapters/_form.html.haml
= simple_form_for([book, chapter]) do |f|
  - if chapter.errors.any?
    #error_explanation
      %h2
        = pluralize(chapter.errors.count, "error")
        prohibited this chapter from being saved:

      %ul
        - chapter.errors.full_messages.each do |msg|
          %li= msg

  .inputs
    = f.input :title

  .actions
    = f.button :submit

app/views/chapters/edit.html.haml
%h1 Editing chapter

= render 'form'

= link_to 'index', book_chapters_path(book)

app/views/chapters/index.html.haml
%h1=book.title

%table
  %tr
    %th index
    %th
    %th

  - chapters.each do |chapter|
    %tr
      %td= link_to chapter.title, book_chapter_sentences_path(book, chapter)
      %td= link_to 'Edit', edit_book_chapter_path(book,chapter)
      %td= link_to 'Destroy', [book, chapter]

%br

= link_to 'New Chapter', new_book_chapter_path

app/views/chapters/new.html.haml
%h1 New chapter

= render 'form'

= link_to 'Back', book_chapters_path(book)

app/views/chapters/show.html.haml
%p#notice= notice

%p
  %b Title:
  = chapter.title
%p
  %b Book:
  = chapter.book

= link_to 'Edit', edit_book_chapter_path(book, chapter)
\|
= link_to 'Back', book_chapters_path

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
  %head
    %title= content_for?(:title) ? yield(:title) : "Chamber"
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
    = csrf_meta_tag
    = yield(:head)
  %body
    %div#container
      - flash.each do |name, msg|
        =content_tag :div, msg, :id => "flash_#{name}"
      %h1=(yield(:title) if show_title?)
      = yield

app/views/sentences/_form.html.haml
= simple_form_for([book, chapter, sentence]) do |f|
  = f.error_notification

  .inputs
    = f.input :text
    = f.input :type

  .actions
    = f.button :submit

app/views/sentences/edit.html.haml
%h1 Editing sentence

= render 'form'

= link_to 'Show', [book,chapter,sentence]
\|
= link_to 'Back', book_chapter_sentences_path(book,chapter)

app/views/sentences/index.html.haml
%h1=chapter.title

%table
  %tr
    %th Text
    %th Type
    %th
    %th
    %th

  - sentences.each do |sentence|
    %tr
      %td= sentence.text
      %td= sentence.type
      %td= link_to 'Show', [book,chapter,sentence]
      %td= link_to 'Edit', edit_book_chapter_sentence_path(book,chapter,sentence)
      %td= link_to 'Destroy', [book,chapter,sentence], :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Sentence', new_book_chapter_sentence_path(book,chapter)

app/views/sentences/new.html.haml
%h1 New sentence

= render 'form'

= link_to 'Back', book_chapter_sentences_path(book,chapter)

app/views/sentences/show.html.haml
%p#notice= notice

%p
  %b Text:
  = sentence.text
%p
  %b Type:
  = sentence.type

= link_to 'Edit', edit_book_chapter_sentence_path(book,chapter,sentence)
\|
= link_to 'Back', book_chapter_sentences_path(book,chapter)